name: Validate PVCollada XML examples

on:
  push:
    paths:
      - schema/pvcollada_schema_0.1.xsd
      - schema/collada_schema_1_5.xsd
      - .github/workflows/validate_xml_with_xsd.py

      - Examples/05 - VerySimpleFixedPVC2_with_electrical_layout_v3.pvc
  pull_request:
    paths:
      - schema/pvcollada_schema_0.1.xsd
      - schema/collada_schema_1_5.xsd
      - .github/workflows/validate_xml_with_xsd.py

      - Examples/05 - VerySimpleFixedPVC2_with_electrical_layout_v3.pvc
  workflow_dispatch:

jobs:
  validate-schema:
    strategy:
      matrix:
        xml_doc:
          - Examples/05 - VerySimpleFixedPVC2_with_electrical_layout_v3.pvc
    name: Validate XML
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install lxml Python dependency
        run: pip3 install lxml==5.3.1
      - name: Checkout PVCollada and COLLADA schemas, the validation script, and the XML doc
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            schema/pvcollada_schema_0.1.xsd
            schema/collada_schema_1_5.xsd
            .github/workflows/validate_xml_with_xsd.py
            ${{ matrix.xml_doc }}
          sparse-checkout-cone-mode: false
      - name: Run validation
        working-directory: schema
        run: python3 "$GITHUB_WORKSPACE"/.github/workflows/validate_xml_with_xsd.py pvcollada_schema_0.1.xsd "$GITHUB_WORKSPACE"/"${{ matrix.xml_doc }}"
